name: advanced_column_row
description: "A new Flutter package that provides advanced column and row widgets."
version: 1.0.0
homepage: https://github.com/Achintha444/advanced_column_row
repository: https://github.com/Achintha444/advanced_column_row
issue_tracker: https://github.com/Achintha444/advanced_column_row/issues
documentation: https://github.com/Achintha444/advanced_column_row/blob/main/README.md
topics: [column, row, widgets]

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
